### ISSUE TITLE
Dependence MewCore

### ISSUE THREAD

**Issue by emil-x** [Akiranya/GemsEconomy#1]
Hello.
I can't find the "MewCore" dependency, plugins don't want to build without it

// My own library
compileOnlyApi("cc.mewcraft:MewCore:5.13.1")

I also couldn't find the repository for dependency

**Comment by Akiranya** [comment]
Hi,

MewCore is my personal mini library, so you are on your own way to figure it out :)

As a side note, this fork is mainly for my personal use and I make it public just for learning purpose
